platform :ios, '8.0'
use_frameworks!

target 'SettingsBundleViewController_Example' do
  pod 'SettingsBundleViewController', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SettingsBundleViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

post_install do | installer |
  require 'fileutils'

  FileUtils.cp_r('Pods/Target Support Files/Pods-SettingsBundleViewController_Example/Pods-SettingsBundleViewController_Example-acknowledgements.plist', 'SettingsBundleViewController/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
