platform :ios, '9.0'
use_frameworks!

target 'SettingsBundleViewController_Example' do
  pod 'SettingsBundleViewController', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SettingsBundleViewController_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end

post_install do | installer |
  require 'fileutils'

  FileUtils.cp_r('Pods/Target Support Files/Pods-SettingsBundleViewController_Example/Pods-SettingsBundleViewController_Example-acknowledgements.plist', 'SettingsBundleViewController/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
